# from turtle import Turtle, Screen
# aamesh = Turtle()
# print(aamesh)
# aamesh.shape("turtle")
# aamesh.pensize(5)
# aamesh.color("green")
#
# aamesh.forward(100)
# aamesh.color("coral")
# aamesh.circle(150)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.color("black")
# aamesh.circle(140)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.color("yellow")
# aamesh.circle(130)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.color("blue")
# aamesh.circle(120)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.color("purple")
# aamesh.circle(110)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.color("indigo")
# aamesh.right(45)
# aamesh.color("red")
# aamesh.forward(125)
# aamesh.left(25)
# aamesh.color("blue")
# aamesh.forward(200)
# aamesh.right(66)
# aamesh.forward(98)
# aamesh.circle(50)
# aamesh.left(90)
# aamesh.color("cyan")
# aamesh.circle(75)
# aamesh.forward(10)
# aamesh.circle(67)
#
# my_screen = Screen()
# print(my_screen.canvheight)
# my_screen.exitonclick()
# import prettytable